import 'package:music_player_ui/models/album_model.dart';

List<AlbumModel> albumsList = [
  AlbumModel(
    albumPhoto: 'assets/pictures/cd_1.png',
    albumName: 'Album 1',
    albumSinger: 'Black Sabbath',
    songsList: [
      SongModel(songName: 'End of the Beginning', songDuration: 6.40),
      SongModel(songName: 'God is Dead?', songDuration: 4.40),
      SongModel(songName: 'Loner', songDuration: 2.50),
      SongModel(songName: 'Zeitgeist', songDuration: 4.33),
      SongModel(songName: 'Age of Reason', songDuration: 6.20),
      SongModel(songName: 'Live forever', songDuration: 3.25),
      SongModel(songName: 'Damage Soul', songDuration: 4.20),
      SongModel(songName: 'End of the Beginning', songDuration: 4.55),
      SongModel(songName: 'God is Dead?', songDuration: 6.40),
      SongModel(songName: 'Loner', songDuration: 3.25),
    ],
  ),
  AlbumModel(
    albumPhoto: 'assets/pictures/cd_2.png',
    albumName: 'Album 2',
    albumSinger: 'Black Sabbath',
    songsList: [
      SongModel(songName: 'Live forever', songDuration: 3.25),
      SongModel(songName: 'Age of Reason', songDuration: 6.20),
      SongModel(songName: 'Loner', songDuration: 2.50),
      SongModel(songName: 'Zeitgeist', songDuration: 4.33),
      SongModel(songName: 'Loner', songDuration: 3.25),
      SongModel(songName: 'God is Dead?', songDuration: 4.40),
      SongModel(songName: 'Damage Soul', songDuration: 4.20),
      SongModel(songName: 'End of the Beginning', songDuration: 6.40),
      SongModel(songName: 'God is Dead?', songDuration: 6.40),
      SongModel(songName: 'End of the Beginning', songDuration: 4.55),
    ],
  ),
  AlbumModel(
    albumPhoto: 'assets/pictures/cd_3.png',
    albumName: 'Album 3',
    albumSinger: 'Black Sabbath',
    songsList: [
      SongModel(songName: 'Loner', songDuration: 2.50),
      SongModel(songName: 'Zeitgeist', songDuration: 4.33),
      SongModel(songName: 'Age of Reason', songDuration: 6.20),
      SongModel(songName: 'Live forever', songDuration: 3.25),
      SongModel(songName: 'End of the Beginning', songDuration: 6.40),
      SongModel(songName: 'End of the Beginning', songDuration: 4.55),
      SongModel(songName: 'God is Dead?', songDuration: 4.40),
      SongModel(songName: 'Damage Soul', songDuration: 4.20),
      SongModel(songName: 'Loner', songDuration: 3.25),
      SongModel(songName: 'God is Dead?', songDuration: 6.40),
    ],
  ),
  AlbumModel(
    albumPhoto: 'assets/pictures/cd_4.png',
    albumName: 'Album 4',
    albumSinger: 'Black Sabbath',
    songsList: [
      SongModel(songName: 'God is Dead?', songDuration: 4.40),
      SongModel(songName: 'Loner', songDuration: 2.50),
      SongModel(songName: 'End of the Beginning', songDuration: 4.55),
      SongModel(songName: 'Age of Reason', songDuration: 6.20),
      SongModel(songName: 'End of the Beginning', songDuration: 6.40),
      SongModel(songName: 'Damage Soul', songDuration: 4.20),
      SongModel(songName: 'Live forever', songDuration: 3.25),
      SongModel(songName: 'Zeitgeist', songDuration: 4.33),
      SongModel(songName: 'God is Dead?', songDuration: 6.40),
      SongModel(songName: 'Loner', songDuration: 3.25),
    ],
  ),
  AlbumModel(
    albumPhoto: 'assets/pictures/cd_5.png',
    albumName: 'Album 5',
    albumSinger: 'Black Sabbath',
    songsList: [
      SongModel(songName: 'Damage Soul', songDuration: 4.20),
      SongModel(songName: 'God is Dead?', songDuration: 4.40),
      SongModel(songName: 'Loner', songDuration: 2.50),
      SongModel(songName: 'Age of Reason', songDuration: 6.20),
      SongModel(songName: 'End of the Beginning', songDuration: 6.40),
      SongModel(songName: 'Live forever', songDuration: 3.25),
      SongModel(songName: 'End of the Beginning', songDuration: 4.55),
      SongModel(songName: 'Zeitgeist', songDuration: 4.33),
      SongModel(songName: 'God is Dead?', songDuration: 6.40),
      SongModel(songName: 'Loner', songDuration: 3.25),
    ],
  ),
  AlbumModel(
    albumPhoto: 'assets/pictures/cd_6.png',
    albumName: 'Album 6',
    albumSinger: 'Black Sabbath',
    songsList: [
      SongModel(songName: 'Loner', songDuration: 2.50),
      SongModel(songName: 'End of the Beginning', songDuration: 6.40),
      SongModel(songName: 'God is Dead?', songDuration: 4.40),
      SongModel(songName: 'Zeitgeist', songDuration: 4.33),
      SongModel(songName: 'Age of Reason', songDuration: 6.20),
      SongModel(songName: 'End of the Beginning', songDuration: 4.55),
      SongModel(songName: 'Damage Soul', songDuration: 4.20),
      SongModel(songName: 'Live forever', songDuration: 3.25),
      SongModel(songName: 'God is Dead?', songDuration: 6.40),
      SongModel(songName: 'Loner', songDuration: 3.25),
    ],
  ),
];
